package gui;

import java.awt.HeadlessException;
import java.awt.Image;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;


public class mainMenuFrame extends javax.swing.JFrame {
    ImageIcon icon = new ImageIcon("src/images/icon.png");
    Image symbol = icon.getImage();
    private String user1="";
    private String date="";

    public mainMenuFrame() {
        initComponents();
    }

    
    /** Creates new form mainMenuFrame */
    public mainMenuFrame(String user) {
        initComponents();
        this.user1=user;
        System.out.print(date);
        
        this.setIconImage(symbol);
        //setting the text in the labels
        LogedinLbl.setText("Your are logged in as : " + this.user1);
        dateLbl.setText(date);
        
    }

    mainMenuFrame(String user1, String date) {
        initComponents();
        this.user1=user1;
        this.date=date;
        
        
        this.setIconImage(symbol);
        //setting the text in the labels
        LogedinLbl.setText("Your are logged in as : " + this.user1);
        dateLbl.setText(this.date);
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        imageLabel = new javax.swing.JLabel();
        buttonPanel = new javax.swing.JPanel();
        searchEditButton = new javax.swing.JButton();
        insertButton = new javax.swing.JButton();
        quitButton = new javax.swing.JButton();
        logoffButton = new javax.swing.JButton();
        LogedinLbl = new javax.swing.JLabel();
        dateLbl = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(255, 255, 255));

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));

        imageLabel.setFont(new java.awt.Font("Tahoma", 0, 24));
        imageLabel.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LIT_Logo.jpg"))); // NOI18N
        imageLabel.setText("  LIT Realty - Main Menu");

        buttonPanel.setBackground(new java.awt.Color(255, 255, 255));
        buttonPanel.setLayout(new java.awt.GridLayout(4, 1));

        searchEditButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/search1-32.png"))); // NOI18N
        searchEditButton.setText("Search or Makes Changes");
        searchEditButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchEditButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(searchEditButton);

        insertButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/doc2_insert-32.png"))); // NOI18N
        insertButton.setText("Insert Record");
        insertButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                insertButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(insertButton);

        quitButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/exit-32.png"))); // NOI18N
        quitButton.setText("Quit");
        quitButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                quitButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(quitButton);

        logoffButton.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/LogOff-32.png"))); // NOI18N
        logoffButton.setText("Logoff");
        logoffButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoffButtonActionPerformed(evt);
            }
        });
        buttonPanel.add(logoffButton);

        LogedinLbl.setText("Loged in as: ");

        dateLbl.setText("date");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(imageLabel)
                .addContainerGap(154, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(107, 107, 107)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, 312, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(201, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(368, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(dateLbl)
                    .addComponent(LogedinLbl))
                .addGap(172, 172, 172))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(LogedinLbl)
                .addGap(10, 10, 10)
                .addComponent(dateLbl)
                .addGap(18, 18, 18)
                .addComponent(imageLabel)
                .addGap(37, 37, 37)
                .addComponent(buttonPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void quitButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_quitButtonActionPerformed
        // Quit button terminate the application
        System.exit(0);
    }//GEN-LAST:event_quitButtonActionPerformed

    private void searchEditButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchEditButtonActionPerformed
        try {
            search s = new search(user1, date);
            s.setVisible(true);
            this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_searchEditButtonActionPerformed

    private void logoffButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoffButtonActionPerformed
        try {
            LoginFrame back = new LoginFrame();
            back.userName = "";
            back.userName = null;
            back.password = null;
            back.setVisible(true);
            this.setVisible(false);
            back.setDefaultCloseOperation(DO_NOTHING_ON_CLOSE);
        } catch (ClassNotFoundException ex) {
            Logger.getLogger(mainMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_logoffButtonActionPerformed

    private void insertButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_insertButtonActionPerformed
        try {
            insert next = new insert(user1, date);
            next.setVisible(true);
        this.setVisible(false);
        } catch (SQLException ex) {
            Logger.getLogger(mainMenuFrame.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_insertButtonActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel LogedinLbl;
    private javax.swing.JPanel buttonPanel;
    private javax.swing.JLabel dateLbl;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton insertButton;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JButton logoffButton;
    private javax.swing.JButton quitButton;
    private javax.swing.JButton searchEditButton;
    // End of variables declaration//GEN-END:variables

    private String getUser1() {
        return user1;
    }

    private void setUser1(String user1) {
        this.user1 = user1;
    }

    private String getDate() {
        return date;
    }

    private void setDate(String date) {
        this.date = date;
    }
}
